### ISSUE TITLE
linux compil fails : because you use the IOKitLib API Apple Developper lib ! 

### ISSUE THREAD

**Issue by castett** [bkurtz/NorthStar#1]
experience from the Linux OS : 

compilation fails :+1: 

$ make 
cd src && make
make[1]: Entering directory '/opt/apps/polar/src/NorthStar/src'
cc  -g  -c -o rawhid_api.o rawhid_api.c

rawhid_api.c:35:28: fatal error: IOKit/IOKitLib.h: No such file or directory

compilation terminated.

<builtin>: recipe for target 'rawhid_api.o' failed
make[1]: *** [rawhid_api.o] Error 1
make[1]: Leaving directory '/opt/apps/polar/src/NorthStar/src'
makefile:5: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bkurtz** [comment]
Right, that part where I didn't actually ever bother to test or even build it on linux.  bcfe99520f7fb170a569ed91c49f5764da6297c4 should at least fix the build - my linux box and my watch are not in the same place tonight, so can't test beyond that.
